### ISSUE TITLE
conda-install-od-seq-linux.sh Incorrect directory for OD-seq

### ISSUE THREAD

**Issue by edwardbirdlab** [NUS-pathogen-genomics/ARGDIT#1]
When running conda-install-od-seq-linux.sh I get the error 'mv: cannot stat './OD-seq-src/OD-seq': No such file or directory'. I believe this is because the folder it is referencing is 'OD-Seq-src', so if that is changed in line 41 & 43 it should fix it.

**Comment by jimmykhchiu** [comment]
Hi @edwardbirdlab, thanks for pointing out this problem. It has been fixed.
